services:
  - type: web
    name: zeus-slot-api
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/trpc/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        sync: false
      - key: APP_ID
        sync: false
      - key: APP_SECRET
        sync: false
